<html>
    <head>
        <title>Rice Oligonucleotide Array Database</title>
        <link rel=stylesheet type="text/css" href="../RAD.css">
    </head>

    <body>

        <table>

            <?php include "../inc/ROAD_inc_header.php" ?> 

            <tr>
                <td class="menu" valign="top">

                    <?php include "../inc/ROAD_inc_left_menu.php" ?>

                </td>

                <td width="5">
                </td>

                <td class="main" valign="top" width="600">
                    <!-- INFORMATION GOES UNDERNEATH HERE -->

                    <h2>Welcome to the NSF Rice Oligonucleotide Array Project</h2>
                    <br/>

                    <table cellspacing="10">
                        <tr>
                            <td>
                                <img src="../images/block_1.gif">
                            </td>
                            <td>
                                <img src="../images/block_2.gif">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <img src="../images/block_3.gif">
                            </td>
                            <td>                      
                                <img src="../images/block_4.gif">
                            </td>
                        </tr>
                    </table>


                    <br/>
                    <font color=red><b>Note</b></font>: The UCD ArrayCore facility was closed 10/1/09. Please stop placing order.

                    <br/><br/>
                    Note: Funding for this project ended on September 30, 2007. This site will be maintained for the near future. Arrays can still be ordered through the website and are still being printed at the University of California-Davis facility. Please direct all inquires to: <a href="mailto:pcronald@ucdavis.edu?subject=Rice Oligonucleotide Array">Pam Ronald</a> and <a href="mailto:jmpfeiff@ucdavis.edu?subject=Rice Oligonucleotide Array">Janice Pfeiff</a> regarding availability of the arrays. If there are problems with the website, please email <a href="mailto:peijiancao@gmail.com?subject=Rice Oligonucleotide Array">PeijianCao at gmail dot com</a>.



                    <h3>Xoo Microarray&nbsp;<b style='color: black;'>NEW</b></h3>
                    <br/>

                    The oligo design for the new Xanthomonas oryzae array (4658 Xo oligos corresponding to 1000 oligos unique 
                    to Xanthomonas oryzae pv oryzae, 1000 oligos unique to Xanthomonas oryzae pv oryzicola and 2500 oligos 
                    shared between the 2 genomes) is now complete.  These oligos were designed using <a href="http://www.complex.iastate.edu/download/Picky/">PICKY</a>. 
                    The list of <a href='files/xo_array_384plates_oligos_5k.zip'>oligos</a> (zip, 138K) and their <a href='files/xo_array_orfs_5k.zip'>ORFs</a> (zip, 1.32M) are available for download. 
                    The cost is $110 per 5K array. Orders can be placed on the <a href='order.php'>Order Arrays</a> page.

                    <br/>
                    <br/>

                    <h3>Why Rice Oligonucleotide Arrays?</h3>
                    <br/>

                    Microarray technology permits biologists to concurrently measure the
                    expression levels of thousands of genes in a single experiment.
                    Public-access to microarrays is critical to ensure that the public's large
                    investment in rice genomics is converted to public scientific and economic
                    benefits. 

                    <br/>
                    <br/>

                    Because of its small genome size, extensive genetic map, available genome
                    sequence, and relative ease of transformation, rice is considered a model
                    species for monocots. Gene sequences are relatively conserved among
                    economically agricultural cereal species such as rice, maize, wheat, barley,
                    sorghum, rye, and sugarcane, and therefore, structural and functional
                    analysis of rice has broad practical implications. Draft rice genomic
                    sequence has been generated by <a href="http://www.rice-research.org/">Monsanto</a> (<i>japonica</i> cultivar Nipponbare),
                    <a href="http://www.sciencemag.org/cgi/content/full/296/5565/92">Syngenta</a> (<i>japonica</i> cultivar Nipponbare) and the <a href="http://www.sciencemag.org/cgi/content/full/296/5565/79">Beijing Genomics Institute</a>
                    (<i>indica</i> cultivar). Moreover, <a href="http://www.ncbi.nlm.nih.gov/dbEST/dbEST_summary.html">>260,000 ESTs</a> and <a href="http://www.sciencemag.org/cgi/content/full/301/5631/376">>28,000 full length cDNA</a>
                    sequences are also available.

                    <br/>
                    <br/>

                    <a href="http://rgp.dna.affrc.go.jp/IRGSP/">The International Rice Genome Sequencing Project</a> (IRGSP) has now produced
                    a finished rice (<i>O. sativa</i> spp. <i>japonica</i> cultivar Nipponbare) <a href="http://rgp.dna.affrc.go.jp/IRGSP/download.html">genome
                        sequence</a>.

                    <br/>
                    <br/>

                    The oligo design for the new 45K array (43,312 oligos corresponding to 44,974 TIGR V3 rice gene models) is now complete. 
                    The NSF supported rice oligo 45K  array was
                    designed using gene models from the <a href="http://www.tigr.org/tdb/e2k1/osa1/">TIGR Rice Annotation Database</a> that
                    have EST and/or full-length cDNA support. These oligos were cross referenced
                    to the Kikuchi full-length cDNA dataset and were designed using <a href="http://www.complex.iastate.edu/download/Picky/">PICKY</a>.  The
                    list of oligos may be downloaded <a href='files/rice_45k.oligo.zip'>here</a> (zip file).  
                    The cost per 45K array will be $110. Orders are now being accepted on the <a href="order.php">Order Arrays</a> page.

                    <br/>
                    <br/>

                    <h3>Objectives of the NSF Rice Oligonucleotide Array Project</h3>
                    <br/>

            <li>Design 50-70-mer oligomers based on finished rice genomic sequence.
                </br>
            <li>Distribute 2 generations of rice microarrays. The second version will
                correspond to the "whole genome".
                </br>
            <li>Construct a data analysis system, database and user interface for microarray 
                expression data. Develop web-based tools for data mining the rice transcriptome.
                </br>
            <li>Develop training workshops in plant microarray experimentation.

                <br/>
                <br/>

                <h3>Rice Oligonucleotide Microarray (ROMA) Expression Database</h3>
                <br/>

                The ROMA database at TIGR is designed to support expression data from all publicly available rice array 
                platforms including the NSF Rice Oligonucleotide Array Project, Agilent arrays, Affymetrix arrays, and the 
                Yale/BGI oligonucleotide array. Please note that these publicly available data are available at other repositories 
                such as the <a href='http://www.ncbi.nlm.nih.gov/geo/'>NCBI Gene Expression Omnibus</a> and in the case of the Yale/BGI array, 
                at the <a href='http://plantgenomics.biology.yale.edu/riceatlas/'>Virtual Center for Cellular Expression Profiling of Rice</a>. 
                Please note that we process the expression data using our methods (see URL) and thus our normalized data 
                may differ from that at other expression databases

                <br/>
                <br/>

                <h3>Investigators</h3>
                <br/>

                The NSF Rice Oligonucleotide Array Project is a joint effort by
                <a href="http://www.ucdavis.edu/"> University of California at Davis (UCD)</a>, 
                <a href="http://www.tigr.org/">The Institute for Genomic Research (TIGR)</a> and 
                <a href="http://www.iastate.edu/">Iowa State University (ISU)</a>. The arrays will be 
                printed at<a href="http://array.ucdavis.edu/"> ArrayCore</a> at UCD.

                <br/>
                <br/>

                Investigators:
                <br/>
            <li><a href="http://indica.ucdavis.edu/">Pamela Ronald</a>, Principal Investigator, UCD, <a href="mailto:pcronald@ucdavis.edu?subject=Rice Oligonucleotide Array">pcronald@ucdavis.edu</a></li>
            <li><a href="http://www.tigr.org/faculty/Robin_Buell.php">C. Robin Buell</a>, co-Principal Investigator, TIGR</li>
            <li><a href="http://www.complex.iastate.edu/hhchou/">H. H. Chou</a>, co-Principal Investigator, ISU, <a href="mailto:hhchou@iastate.edu?subject=Rice Oligonucleotide Array">hhchou@iastate.edu</a></li>
            <li><a href="http://www.cipic.ucdavis.edu/~dmrocke">David Rocke</a>, co-Principal Investigator, UCD, <a href="mailto:dmrocke@ucdavis.edu?subject=Rice Oligonucleotide Array">dmrocke@ucdavis.edu</a></li>
            <li><a href="http://schnablelab.plantgenomics.iastate.edu/">Patrick Schnable</a>, co-Principal Investigator, ISU, <a href="mailto:schnable@iastate.edu?subject=Rice Oligonucleotide Array">schnable@iastate.edu</a></li>

            <br/>
            <br/>

            The NSF Rice Oligonucleotide Array Project at UCD, TIGR and ISU was funded by the <a href="http://www.nsf.gov/">National Science Foundation</A>. The project has since ended but arrays are still being printed at the University of California-Davis facility.

            <br/>
            <br/>


            <!-- INFORMATION GOES ABOVE HERE -->

            <br/>
            <br/>
            <font color="#708899">Last modified: <!--#echo var="LAST_MODIFIED" --></font>

        </td>

        <td width="5">
        </td>

        <td class="menu" valign="top">

            <?php include "../inc/ROAD_inc_right_menu.php" ?>

        </td>

    </tr>
</table>
</body>
</html>
