<html>
    <head>
        <title>Rice Oligonucleotide Array Database</title>
        <link rel=stylesheet type="text/css" href="../RAD.css">
    </head>

    <body>

        <table>

            <?php include "../inc/ROAD_inc_header.php" ?> 

            <tr>
                <td class="menu" valign="top">

                    <?php include "../inc/ROAD_inc_left_menu.php" ?>

                </td>

                <td width="5">
                </td>

                <td class="main" valign="top">
                    <!-- INFORMATION GOES UNDERNEATH HERE -->

                    <h2>Rice Oligonucleotide Array Database Overview</h2>
                    <br/>

                    Download the <a href="files/rice_oligo.mar1307.zip">Rice Oligo Array Database</a> (zip, 2.9M) (Updated Mar 13, 2007).

                    <br/>
                    <br/>

                    The oligo sequences for the 45k array are available for <a href='files/rice_45k.oligo.zip'>download</a> (FASTA format) (zip, 967K).
                    <br/>
                    The oligo sequences for the 20k array are available for <a href='files/rice_20k.oligo.zip'>download</a> (FASTA format) (zip, 528K).

                    <br/>
                    <br/>

                    The data types in the Rice Oligonucleotide Microarray Database are the following:

                    <br/>
                    <br/>
                    <br/>
                    <br/>

                    <a name="overview_tigr_id">
                        <b>Rice Oligo ID</b>: a unique identifier generated by TIGR to reference this oligonucleotide. Format: <i>TR######</i>.
                        Oligos numbered TR000001 - TR020440 belong to the 20K array and oligos numbered TR030001 - TR073311
                        belong on the 45K array set (made up of 2 x 23K arrays).
                        Non-TIGR Oligo IDs include Affymetrix (e.g. <a href='http://www-devel.tigr.org/tigr-scripts/ricearray/search/search_basic.pl?search_type=search_contains&search_term=Os.10027.1.S1_at&search_section=search_locus&result_type=result_html'>Os.10027.1.S1_at</a>), 
                        Agilent (e.g. <a href='http://www-devel.tigr.org/tigr-scripts/ricearray/search/search_basic.pl?search_type=search_contains&search_term=A_71_P104391&search_section=search_locus&result_type=result_html'>A_71_P104391</a>) 
                        and Yale/BGI (e.g. <a href='http://www-devel.tigr.org/tigr-scripts/ricearray/search/search_basic.pl?search_type=search_contains&search_term=Os049662_01&search_section=search_locus&result_type=result_html'>Os049662_01</a>) array identifiers.
                    </a>
                    <br/>
                    <br/>

                    <a name="overview_platform">
                        <b>Array Platform</b>: The array platform containing this oligo: NSF 20K, NSF 45K (23K A or 23K B), Affymetrix, Agilent or Yale/BGI.
                        <br/>
                        <br/>


                        <a name="overview_annot">
                            <b>Putative Annotation</b>: The putative gene function assignment is based on
                            either sequence similarity (BLASTP) of the gene model (or in a few cases
                            the full-length cDNA or gene index sequence) with entries in a
                            non-identifical amino acid database or by the presence of Pfam domains
                            within the predicted protein. Click <a href="http://www.tigr.org/tdb/e2k1/osa1/irgsp/eukan_routine_TIGR.shtml">here</a> for more information on the
                            rice gene model annotation process. 
                        </a>
                        <br/>
                        <br/>

                        <a name="overview_match">
                            <b>Match</b>:
                            The sequence this oligo aligns to at 100% length and identity.  Example match IDs include 
                            <a href='http://rice.tigr.org'>TIGR Rice Genome Annotation</a> release 5 models (e.g. <a href='/tigr-scripts/ricearray/search/search_basic.pl?search_type=search_contains&search_term=LOC_Os01g01150.1&search_section=search_locus&result_type=result_html'>LOC_Os01g01150.1</a>, 
                            <a href='/tigr-scripts/ricearray/search/search_basic.pl?search_type=search_contains&search_term=11669.m00474&search_section=search_locus&result_type=result_html'>11669.m00474</a>), 
                            <a href='http://plantta.tigr.org'>TIGR Plant Transcript Assemblies</a> (e.g. <a href='/tigr-scripts/ricearray/search/search_basic.pl?search_type=search_contains&search_term=TA58977_4530&search_section=search_locus&result_type=result_html'>TA58977_4530</a>), 
                            or full length cDNAs (e.g. <a href='/tigr-scripts/ricearray/search/search_basic.pl?search_type=search_contains&search_term=TA58977_4530&search_section=search_locus&result_type=result_html'>AK109021</a>). 

                            <br/>
                            <br/>

                            <a name="overview_type">
                                <b>Match Type</b>:
                                The type of matching sequence this oligo was aligned to: <a href='http://rice.tigr.org'>TIGR Rice Genome Annotation</a>
                                release 5 models, full length cDNAs, <a href='http://plantta.tigr.org'>TIGR Plant Transcript Assemblies</a>, or 
                                <a href='http://rice.tigr.org'>TIGR Rice Genome Annotation</a> pseudomolecules.

                                <br/>
                                <br/>

                                A TIGR locus ID is a gene/locus identified in the <a href='http://rice.tigr.org'>TIGR Rice
                                    Genome Annotation</a> project or a rice full-length cDNA clone in the case
                                the oligo can no longer be mapped to a rice gene model. Gene models are
                                created by running a series of gene prediction programs on the rice
                                genome and improvement of gene model structure with experimental
                                evidence from ESTs and full-length cDNAs.  Click <a href="http://www.tigr.org/tdb/e2k1/osa1/irgsp/eukan_routine_TIGR.shtml">here</a>
                                for more information on the gene prediction process. 
                            </a>
                            <br/>
                            <br/>

                            <a name="overview_go">
                                <b>Plant GO ID</b>: the <a href="http://www.plantontology.org">Gene Ontology</a> identifier(s) assigned to this oligo, if available.
                            </a>
                            <br/>
                            <br/>

                            <a name="overview_tm">
                                <b>Tm</b>: Calculated melting temperature of the designed oligo, in &deg;C, from <a href='http://www.complex.iastate.edu/download/Picky/'>PICKY</a>. 
                            </a>

                            <br/>
                            <br/>

                            <a name="overview_oligo_len">
                                <b>Oligo Length</b>: Length in bp of the designed oligo (50-70).
                            </a>

                            <br/>
                            <br/>

                            <a name="overview_gc_content">
                                <b>GC Content</b>: GC base content of the designed oligo as a percentage of its total length.
                            </a>
                            <br/>
                            <br/>

                            <a name="overview_sequence">
                                <b>Oligo Sequence</b>: The sequence of the oligo.  Clicking 'View oligo alignment' will 
                                open the <a href='http://www.tigr.org/tigr-scripts/osa1_web/gbrowse/rice/'>TIGR Rice Annotation Project Genome Browser</a>.
                            </a>
                            <br/>
                            <br/>


                            <!-- INFORMATION GOES ABOVE HERE -->

                            <br/>
                            <br/>
                            <font color="#708899">Last modified: <!--#echo var="LAST_MODIFIED" --></font>

                            </td>

                            <td width="5">
                            </td>

                            <td class="menu" valign="top">

                                <?php include "../inc/ROAD_inc_right_menu.php" ?>

                            </td>

                            </tr>
                            </table>
                            </body>
                            </html>
