<html>
<head>
    <title>Rice Oligonucleotide Array Database</title>
    <link rel=stylesheet type="text/css" href="../RAD.css">
</head>

<body>
    
    <table>

	<?php include "../inc/ROAD_inc_header.php" ?> 
	
	<tr>
	    <td class="menu" valign="top">

            <?php include "../inc/ROAD_inc_left_menu.php" ?>

	    </td>

        <td width="5">
        </td>

	    <td class="main" valign="top" width="600">
            <!-- INFORMATION GOES UNDERNEATH HERE -->
      	    
            <h2>Rice Array Element Search</h2>
            <br/>

			To determine which probes from each platform mapped to a specific target, each probe was searched
            against a successive series of nucleotide databases to find if that particular oligo
            mapped to any targets at 100% coverage and 100% identity.  If there was a match, that probe
            was considered to be mapped and removed as a list of candidates to be searched against in the following
            round of database searches.  

            <br/>
            <br/>
      
            The databases used were as follows:

            <ol>
                <li>
                    <a href='http://rice.plantbiology.msu.edu/'>MSU/TIGR Rice Genome Annotation</a> v6 cDNAs
                </li>
				<li>
                    <a href='http://rapdb.dna.affrc.go.jp/'>RAP3 Rice Genome Annotation</a> cDNAs
                </li>
                <li>
                    <a href='http://cdna01.dna.affrc.go.jp/cDNA/'>Rice KOME full-length cDNAs</a>
                </li>
            </ol>

            <br/>

            Alignment searches were conducted using <a href='http://blast.ncbi.nlm.nih.gov/Blast.cgi/'>NCBI BLAST</a>.
            In the case of the Affymetrix searches, a probe set was considered to have been mapped if more than half of the entire
            set of designed probes aligned with 100% identity and coverage.
      
            <br/>
			<br/>

			Download the whole <a href="probe.zip">rice array elements information</a> (zip, 7M) (Updated April, 2011).

			<br/>
			<br/>

			The data types in the Rice Array Element Search are the following:

			<br/>
			<br/>

			
			<b>Array Element ID</b>: a unique identifier generated by manufacture to reference this probe.
			<br/>
			<br/>

			<b>Array Platform</b>: The array platform containing this probe: Affymetrix, Agilent 22K, Agilent 44K, BGI/Yale, NSF 20K and NSF 45K (23K A or 23K B).
			<br/>
			<br/>

			<b>Matched Gene ID</b>:
			The sequence this probe aligns to at 100% length and identity.  Example match IDs include 
			<a href='http://rice.plantbiology.msu.edu/'>MSU/TIGR Rice Genome Annotation</a> release 6 models (e.g. LOC_Os01g01010.1), 
			<a href='http://rapdb.dna.affrc.go.jp/'>RAP3</a> (e.g. Os01t0100100-01) and full length cDNAs (e.g. AK058204). 

			<br/>
			<br/>
<!--
			<b>Tm</b>: Calculated melting temperature of the designed oligo, in &deg;C, from <a href='http://www.complex.iastate.edu/download/Picky/'>PICKY</a>. 
			</a>

			<br/>
			<br/>

			
			<b>Oligo Length</b>: Length in bp of the designed oligo (50-70).
			</a>

			<br/>
			<br/>

			
			<b>GC Content</b>: GC base content of the designed oligo as a percentage of its total length.
			</a>
			<br/>
			<br/>

-->
			
			<b>Probe Sequence</b>: The sequence of the probe.  
			<!-- Clicking 'View oligo alignment' will open the <a href='http://www.tigr.org/tigr-scripts/osa1_web/gbrowse/rice/'>TIGR Rice Annotation Project Genome Browser</a>.-->
			</a>
			<br/>
			<br/>


			<!-- INFORMATION GOES ABOVE HERE -->

			<br/>
			<br/>
			<font color="#708899">Last modified: <!--#echo var="LAST_MODIFIED" --></font>

		</td>

		<td width="5">
		</td>

		<td class="menu" valign="top">

            <?php include "../inc/ROAD_inc_right_menu.php" ?>

	    </td>

	</tr>
    </table>
</body>
</html>
